# Generated by Django 5.2.7 on 2025-10-03 00:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_produto_margem_lucro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade vendida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário no momento da venda', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_venda', models.DateTimeField(auto_now_add=True, help_text='Data e hora da venda')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a venda', null=True)),
                ('total', models.DecimalField(decimal_places=2, editable=False, help_text='Valor total da venda (quantidade × valor unitário)', max_digits=12)),
                ('custo_total', models.DecimalField(decimal_places=2, editable=False, help_text='Custo total dos produtos vendidos', max_digits=12)),
                ('lucro_total', models.DecimalField(decimal_places=2, editable=False, help_text='Lucro total da venda', max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='financeiro.produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
