# Generated by Django 5.2.7 on 2025-10-03 01:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da despesa', max_length=200)),
                ('categoria', models.CharField(choices=[('operacional', 'Operacional'), ('marketing', 'Marketing'), ('administrativo', 'Administrativo'), ('tecnologia', 'Tecnologia'), ('recursos_humanos', 'Recursos Humanos'), ('financeiro', 'Financeiro'), ('juridico', 'Jurídico'), ('infraestrutura', 'Infraestrutura'), ('outros', 'Outros')], default='operacional', help_text='Categoria da despesa', max_length=50)),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor da despesa em reais', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_despesa', models.DateTimeField(auto_now_add=True, help_text='Data e hora da despesa')),
                ('data_vencimento', models.DateField(blank=True, help_text='Data de vencimento (opcional)', null=True)),
                ('pago', models.BooleanField(default=False, help_text='Indica se a despesa foi paga')),
                ('data_pagamento', models.DateTimeField(blank=True, help_text='Data e hora do pagamento', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a despesa', null=True)),
                ('recorrente', models.BooleanField(default=False, help_text='Indica se é uma despesa recorrente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa'],
            },
        ),
    ]
