# Generated by Django 5.2.7 on 2025-10-03 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_despesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que registrou a despesa', on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que criou o produto', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que registrou a venda', on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
